@startuml
    class "注文"{
        合計
    }

    class "注文明細"{
        数量
        小計
    }

    class "割引クーポン"{
        値引き額
        期限
    }

    class "カップ"{
        サイズ
    }

    class "ドリンク"{
        種別
    }

    class "フード"{
    }

    class "商品"{
        名称
        単価
    }


    class "材料"{
    }

    class "ハンバーガー"{
        種別
    }


    class "レシピ"{
    }

    class "ポテト"{
        サイズ
    }

    class "パン"{
    }

    class "肉"{
    }

    class "野菜"{
    }

    class "チーズ"{
    }

    注文 "1..*" o-right- 注文明細
    注文明細 "0..*" -right- "0..1" 割引クーポン
    注文明細 "0..*" -- "1" 商品

    カップ "1..3" -right- "0.." ドリンク
    ドリンク -right-|> 商品

    フード -up-|> 商品
    フード "1" -right- "1" レシピ

    ハンバーガー -up-|> フード
    ポテト -up-|> フード
    ハンバーガー "1..*" o-left- "1..*" 材料

    パン -up-|> 材料
    肉 -up-|> 材料
    野菜 -up-|> 材料
    チーズ -up-|> 材料
    hide circle 
    hide members
    show fields
@enduml