@startuml
class 利用者 {
    - 名前
    - 住所
    - 電話番号
}
class ホテル {
    - 部屋
}
class 部屋 {
    - タイプ
    - 価格
    - キャンペーン価格
}
class 予約 {
    - チェックイン日
    - 滞在期間
    - 値段
}
ホテル "1" *-down- "*" 部屋
ホテル -right- 利用者: < 会員
利用者 "1" -down- "1" 予約
部屋 "1" -right- "*" 予約
@enduml