@startuml
    ' left to right direction
    state c <<choice>>
    [*] -> メニュー画面
    メニュー画面 --> 予約と確認画面
    メニュー画面 --> 今の順番 : 今の順番
    今の順番 -> メニュー画面 : メニューへ
    予約と確認画面 --> c
    c -> あなたの順番画面 : 登録
    c -> あなたの順番画面 : 確認
    あなたの順番画面 --> メニュー画面 : メニューへ
    c -> メニュー画面 : 取消
    メニュー画面 -right-> [*]
@enduml