@startuml 演習2-3
actor 利用者 #DDDDDD;line:black;line.bold;
rectangle ホテル宿泊予約{
usecase ログイン
usecase キャンペーン
usecase (<u>予約</u>\n拡張点\nキャンペーン期間) as input
}
input <-- 利用者
キャンペーン .> input: << extend >>
input .> ログイン: << include >>
@enduml