@startuml
    left to right direction
    [*] -> 料金投入待ち
    料金投入待ち --> ボタン選択待ち : 料金投入完了
    ボタン選択待ち --> ドリンク排出中 : ボタン選択完了
    ボタン選択待ち --> 料金投入待ち : 返却レバー引く
    ドリンク排出中 --> 料金投入待ち : ドリンク排出完了
    料金投入待ち -> [*]
@enduml