@startuml
    left to right direction
    actor 利用者 as user #DDDDDD;line:black;
    actor 看護師 as nurse #DDDDDD;line:black;line.bold;
    rectangle 診察予約システム{
        usecase 予約を登録する
        usecase 予約情報を確認する
        usecase 予約取り消しをする
        usecase 今の順番を閲覧する
        usecase 患者番号を増加させる
    }
    user --> 予約を登録する
    user --> 予約情報を確認する
    user --> 予約取り消しをする
    user --> 今の順番を閲覧する
    nurse --> 患者番号を増加させる 
@enduml