@startuml ユースケース図
actor 利用者 #DDDDDD;line:black;line.bold;
rectangle ホテル宿泊予約 {

usecase ログイン
usecase 予約
usecase (<u>予約</u>\n拡張期間\nキャンペーン期間) as input
usecase キャンペーン

}

ログイン <. 予約 : <<　include　 >> 
利用者-->予約
@enduml