@startuml
left to right direction
class 医師 {

}
class 患者 {

}
class 医局 {
- 外科
- 内科
- 小児科
}
class 診察記録作成 {

}
医師 "1" --> "*" 患者: <<診察>>
医局 "1" o-- "*" 医師:<<所属>>
医師 "*" --> "*" 診察記録作成: <<診察の都度作成>>
診察記録作成 "1" -- "1" 患者
@enduml