@startuml
left to right direction
object "<u>ホテル情報: ホテル</u>" as h{
    ホテル名=ホテルUML
    住所
    キャンペーン期間=4月29日～5月6日
}
object "<u>301号室: 客室</u>" as r1{
    部屋番号=301
    部屋タイプ=シングル
    宿泊費=11,000円
    キャンペーン価格=9,000円
}
object "<u>利用者情報1: 利用者</u>" as u1{
    利用者名=Aさん
    電話番号
}
object "<u>利用者情報2: 利用者</u>" as u2{
    利用者名=Bさん
    電話番号
}
object "<u>303号室: 客室</u>" as r2{
    部屋番号=303
    部屋タイプ=シングル
    宿泊費=11,000円
    キャンペーン価格=9,000円
}
object "<u>302号室: 客室</u>" as r2{
    部屋番号=302
    部屋タイプ=シングル
    宿泊費=11,000円
    キャンペーン価格=9,000円
}
h -- r1
h -- r2
r1 -- u1
r2 -- u2
@enduml